version: "3"
services:
  prison-to-nhs-update:
    image: quay.io/hmpps/prison-to-nhs-update:latest
    network_mode: "host"
    container_name: prison-to-nhs-update
    depends_on:
      - localstack
      - elite2-api
      - prison-estate
    ports:
      - "8084:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]
    environment:
      - SERVER_PORT=8080
      - API_BASE_URL_OAUTH=http://localhost:8090/auth
      - API_BASE_URL_NOMIS=http://localhost:8093
      - API_BASE_URL_PRISON_ESTATE=http://localhost:7070
      - API_BASE_URL_NHS=http://localhost:7080
      - SQS_ENDPOINT_URL=http://localhost:4576
      - SQS_PROVIDER=localstack
      - SQS_AWS_ACCESS_KEY_ID=foobar
      - SQS_AWS_SECRET_ACCESS_KEY=foobar
      - SQS_DEFAULT_REGION=eu-west-2
      - OAUTH_CLIENT_SECRET=clientsecret
      - OAUTH_CLIENT_ID=prison-to-nhs-update-api-client

  elite2-api:
    image: quay.io/hmpps/prison-api:latest
    container_name: elite2-api
    depends_on:
      - oauth
    ports:
      - "8093:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb

  oauth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: oauth
    ports:
      - "8090:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  prison-estate:
    image: quay.io/hmpps/prison-estate:latest
    networks:
      - hmpps
    container_name: prison-estate
    ports:
      - "8094:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  localstack:
    image: localstack/localstack:0.12.9.1
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566-4597:4566-4597"
    environment:
      - SERVICES=sqs,sns
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock

      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./src/test/resources/localstack:/docker-entrypoint-initaws.d

networks:
  hmpps:
