info.app:
  name: HMPPS Prison To NHS Update
  version: 1.0

spring:
  application:
    name: prison-to-nhs-update

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  codec:
    max-in-memory-size: 10MB

  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false

  flyway:
    enabled: true
    baselineOnMigrate: true
    schemas: NHS_OFFENDER
    locations: classpath:/db/migration/h2,classpath:/db/migration/common
    url: 'jdbc:h2:mem:nhs-offender-db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1'
    user: sa
    password: ''
    placeholders:
      database_password: dummy

  datasource:
    # This reopens the H2 database prepared by flyway with default schema and user OFFENDER_EVENTS
    url: 'jdbc:h2:mem:nhs-offender-db;MODE=PostgreSQL;SCHEMA=NHS_OFFENDER;IFEXISTS=TRUE'
    continue-on-error: true
    username: nhs_offender
    password: dummy

    hikari:
      pool-name: NhsOffender-CP
      connectionTimeout: 1000
      validationTimeout:  500

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${api.base.url.oauth}/.well-known/jwks.json

      client:
        registration:
          nomis-api:
            provider: hmpps-auth
            client-id: ${oauth.client.id}
            client-secret: ${oauth.client.secret}
            authorization-grant-type: client_credentials
            scope: read
        provider:
          hmpps-auth:
            token-uri: ${api.base.url.oauth}/oauth/token
server:
  port: 8082
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol_header: x-forwarded-proto
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms

prisontonhs:
  only.prisons: ''

sqs:
  provider: aws
  queue.name: prison_to_nhs_queue
  dlq.name: prison_to_nhs_dlq
  endpoint.region: eu-west-2

azure:
  application-insights.web.enable-W3C: true

applicationinsights:
  connection:
    string: InstrumentationKey=${application.insights.ikey}
