sqs:
  provider: localstack
  endpoint:
    url: http://localhost:4576

elite2:
  endpoint:
    url: http://localhost:8093

oauth:
  client:
    id: prison-to-nhs-update-api-client
    secret: clientsecret
  endpoint:
    url: http://localhost:8090/auth

