---
# Environment specific values, override helm_deploy/prison-to-probation-update/values.yaml
generic-service:
  replicaCount: 2
  ingress:
    host: prison-to-nhs-update-preprod.prison.service.justice.gov.uk
  
  env:
    API_BASE_URL_OAUTH: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_NOMIS: "https://api-preprod.prison.service.justice.gov.uk"
    API_BASE_URL_PRISON_REGISTER: "https://prison-register-preprod.hmpps.service.justice.gov.uk"
    API_BASE_URL_NHS: "http://localhost:9090"
    PRISONTONHS_ONLY_PRISONS: "LEI,MDI,LPI,HLI"
    NHS_SERVER_ENABLED: "false"
  
# CloudPlatform AlertManager receiver to route promethues alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
