---
# Environment specific values, override helm_deploy/prison-to-probation-update/values.yaml
generic-service:
  replicaCount: 2
  ingress:
    host: prison-to-nhs-update-dev.prison.service.justice.gov.uk

  allowlist: null

  env:
    API_BASE_URL_OAUTH: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_NOMIS: "https://api-dev.prison.service.justice.gov.uk"
    API_BASE_URL_PRISON_REGISTER: "https://prison-register-dev.hmpps.service.justice.gov.uk"
    API_BASE_URL_NHS: "http://localhost:9090"
    PRISONTONHS_ONLY_PRISONS: "MDI,LEI,PVI,BXI,LPI,HLI"
    NHS_SERVER_ENABLED: "false"

