# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/prison-to-nhs-update
  tag: latest
  pullPolicy: Always
  port: 8080

ingress:
  enabled: true
  enable_whitelist: false
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: prison-to-nhs-update-dev.prison.service.justice.gov.uk
      cert_secret: prison-to-nhs-update-cert
  path: /

env:
  JAVA_OPTS: "-Xmx512m"
  API_BASE_URL_OAUTH: "https://gateway.t3.nomis-api.hmpps.dsd.io/auth"
  API_BASE_URL_NOMIS: "https://gateway.t3.nomis-api.hmpps.dsd.io/elite2api"
  API_BASE_URL_PRISON_ESTATE: "https://estate-dev.prison.service.justice.gov.uk"
  API_BASE_URL_NHS: "http://localhost:9090"
  PRISONTONHS_ONLY_PRISONS: "MDI,LEI,PVI,BXI,LPI,HLI"
  NHS_SERVER_ENABLED: "false"


