---
# Environment specific values, override helm_deploy/prison-to-probation-update/values.yaml
generic-service:
  replicaCount: 2
  ingress:
    host: prison-to-nhs-update.prison.service.justice.gov.uk

  env:
    JAVA_OPTS: "-Xmx512m"
    API_BASE_URL_OAUTH: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_NOMIS: "https://api.prison.service.justice.gov.uk"
    API_BASE_URL_PRISON_REGISTER: "https://prison-register.hmpps.service.justice.gov.uk"
    API_BASE_URL_NHS: "http://localhost:9090"
    PRISONTONHS_ONLY_PRISONS: "LEI,MDI,LPI,HLI"
    NHS_SERVER_ENABLED: "false"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
  
# determine which slack channel alerts are sent to, via the correct Alert Manager receiver
generic-prometheus-alerts:
  alertSeverity: digital-prison-service
