---
# Values here are the same across all environments
generic-service:
  nameOverride: prison-to-nhs-update

  image:
    repository: quay.io/hmpps/prison-to-nhs-update
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/custom-http-errors: "418"
    tlsSecretName: prison-to-nhs-update-cert
    path: /


  env:
    SERVER_PORT: 8080
    SPRING_PROFILES_ACTIVE: "postgres,logstash"
    JAVA_OPTS: "-Xmx512m"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    prison-to-nhs-update:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      OAUTH_CLIENT_ID: "PRISON_TO_NHS_CLIENT_ID"
      OAUTH_CLIENT_SECRET: "PRISON_TO_NHS_CLIENT_SECRET"
    ptnhs-sqs-instance-output:
      HMPPS_SQS_QUEUES_EVENT_QUEUE_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_EVENT_QUEUE_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_EVENT_QUEUE_NAME: "sqs_ptnhs_name"
    ptnhs-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_EVENT_DLQ_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_EVENT_DLQ_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_QUEUES_EVENT_DLQ_NAME: "sqs_ptnhs_name"
    dps-rds-instance-output:
      DATABASE_PASSWORD: "prison_to_nhs_update_password"
      SUPERUSER_USERNAME: "database_username"
      SUPERUSER_PASSWORD: "database_password"
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: prison-to-nhs-update
